config/routes.rb
Rails.application.routes.draw do
  resources :reviews, :pets, :locations, :types, :topics,  :comments, :users
  devise_for :users, path: '', path_names:{ sign_in: 'login',  sign_out: 'logout', sessions: ''}
  root 'users#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/pet.rb
class Pet < ApplicationRecord
  belongs_to :user
  belongs_to :location
  has_many :review, dependent: :destroy
  has_many :pet_type, dependent: :destroy
  has_many :type, through: :pet_type
  mount_uploader :image, ImageUploader

  def set_user!(user)
    self.user_id = user.id
    self.save!
  end
end

app/models/pet_type.rb
class PetType < ApplicationRecord
  belongs_to :type
  belongs_to :pet
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :update, :destroy]
  before_action :set_pet, only: [:show, :edit, :update, :destroy]

  # GET /pets
  # GET /pets.json
  def index
    @pets = Pet.all
  end

  # GET /pets/1
  # GET /pets/1.json
  def show
    review = @pet.review
    @pet.rating = review.average(:rating)
  end

  # GET /pets/new
  def new
    @pet = Pet.new
  end

  # GET /pets/1/edit
  def edit
  end

  # POST /pets
  # POST /pets.json
  def create
    @pet = Pet.new(pet_params)
    @pet.set_user!(current_user)
  
    respond_to do |format|
      if @pet.save
        format.html { redirect_to @pet}
        format.json { render :show, status: :created, location: @pet }
      else
        format.html { render :new }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pets/1
  # PATCH/PUT /pets/1.json
  def update
    respond_to do |format|
      if @pet.update(pet_params)
        format.html { redirect_to @pet}
        format.json { render :show, status: :ok, location: @pet }
      else
        format.html { render :edit }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pets/1
  # DELETE /pets/1.json
  def destroy
    @pet.destroy
    respond_to do |format|
      format.html { redirect_to users_url}
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pet
      @pet = Pet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pet_params
      params.require(:pet).permit(:names, :date_of_birth, :rating, :location_id, :image, type_ids: [])
    end
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/pets/_form.html.erb
<%= form_with(model: pet, local: true) do |form| %>
  <% if pet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pet.errors.count, "error") %> prohibited this pet from being saved:</h2>
      <ul>
        <% pet.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :image %>
    <%= form.file_field :image, class: "form-control-file" %>
  </div>

  <div class="form-group">
    <%= form.label :names %>
    <%= form.text_field :names, class:"form-control"%>
  </div>

  <div class="form-group">
    <%= form.label :date_of_birth %>
    <%= form.date_select :date_of_birth, class:"form-control" %>
  </div>
 
  <div class="form-group">
    <%= form.label :types %>
    <%= form.collection_select(:type_ids, Type.all, :id, :name, { :prompt => 'Select a Type', :selected => @pet.type_ids }, {:multiple => true,  class: 'form-control' })%>
  </div>

  <div class="form-group">
    <%= form.label :location %>
    <%= form.collection_select(:location_id, Location.all, :id, :city, { :prompt => 'Select a Location', :selected => @pet.location_id }, { class: 'form-control' }) %>
  </div>

  <div class="actions float-right">
    <%= form.submit 'Save Pet', :class => "btn btn-primary my-2"%>
  </div>
<% end %>

app/views/pets/edit.html.erb
<div class="card">
  <div class="card-body">
    <h5 class="card-title"><h1>Editing Pet</h1></h5>
    <%= render 'form', pet: @pet %>
    <%= link_to 'Back', users_path, class:"btn btn-primary my-2" %>
  </div>
</div>

app/views/pets/index.html.erb
<main role="main">
      <section class="jumbotron text-center">
        <div class="container">
          <h1 class="jumbotron-heading">Pets</h1>
        </div>
      </section>
      <div class="py-5 bg-light">
        <div class="container">
          <div class="row">
            <% @pets.each do |pet| %>
              <div class="col-md-4">
                <div class="card mb-4 shadow-sm">
                  <%= image_tag(pet.image.url, alt: "/assets/pet.png", class: "card-img-top") if pet.image? %>
                  <div class="card-body">
                    <h5 class="card-title"><%= pet.names%></h5>
                    <h6 class="card-subtitle mb-2 text-muted"><%= pet.rating %></h6>
                    <p class="card-text">
                      <%= pet.location.city %>,
                      <%= pet.location.state %>,
                      <%= pet.location.country %>
                    </p>
                    <div class="d-flex justify-content-between align-items-center">
                      <div class="btn-group">
                        <%= link_to 'Review', new_review_path(:pet => pet), class:"btn btn-sm btn-outline-primary"%>
                        <%= link_to 'Profile', pet, class:"btn btn-sm btn-outline-secondary"%>
                        <% if user_signed_in?%>
                          <% if current_user.id == pet.user.id%>
                            <%= link_to 'Edit', edit_pet_path(pet), class:"btn btn-sm btn-outline-secondary"%>
                            <%= link_to 'Delete', pet, method: :delete, data: { confirm: 'Are you sure?'}, class:"btn btn-sm btn-outline-secondary"%>
                          <% end %>
                        <% end %>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </main>

app/views/pets/new.html.erb
<div class="card">
  <div class="card-body">
    <h5 class="card-title"><h1>New Pet</h1></h5>
    <%= render 'form', pet: @pet %>
    <%= link_to 'Back',pets_path, class:"btn btn-primary my-2" %>
  </div>
</div>

app/views/pets/show.html.erb
<div class="container-fluid">
      <div class="row">
        <div class="sidebar card ">
          <%= image_tag(@pet.image.url, alt: "/assets/pet.png", class: "placeholder card-img-top") if @pet.image? %>
          <ul class="nav nav-sidebar card-body">
            <li>
              <p>
                <strong>Names:</strong>
                <%= @pet.names %>
              </p>
            </li>
            <li>
              <p>
                <strong>User:</strong>
                <%= @pet.user.email %>
              </p>
            </li>
            <li>
              <p>
                <strong>Rating:</strong>
                <%= @pet.rating %>
              </p>
            </li>
            <li>
              <p>
                <strong>Location:</strong>
                <%= @pet.location.city %>, <%= @pet.location.state %>, <%= @pet.location.country%>
              </p>
            </li>
            <li>
              <p>
                <strong>Date of Birth:</strong>
                <%= @pet.date_of_birth %>
              </p>
            </li>
          </ul>
          <div class="btn-group">
            <% if user_signed_in?%>
              <%= link_to 'Review', new_review_path(:pet => @pet), class:"btn btn-sm btn-outline-primary" %>
              <% if current_user.id == @pet.user.id%>
                <%= link_to 'Edit', edit_pet_path(@pet), class:"btn btn-sm btn-outline-secondary" %>
                <%= link_to 'Delete', @pet, method: :delete, data: { confirm: 'Are you sure?'}, class:"btn btn-sm btn-outline-secondary"%>
              <% end %>
            <% end %>
          </div>
        </div>
        <div class="col-sm-12 main">
          <div class="row">
            <div class="card-columns">
              <% @pet.type.each do |t| %>
                <div class="card">
                  <div class="card-body">
                    <h5 class="card-title"><%= t.name %></h5>
                  </div>
                </div>
              <% end %>
            </div>
          </div>
          <div class="row">
            <div class="card-columns">
              <% @pet.review.each do |r| %>
                <div class="card">
                  <div class="card-body">
                    <h4 class="card-title"><%= r.rating %></h4>
                    <h5 class="card-title"><%= r.title %></h5>
                    <h6 class="card-subtitle mb-2 text-muted"><%= r.user.email %></h6>
                    <%= link_to 'Read', r %>
                    <% if user_signed_in?%>
                      <% if current_user.id == r.user.id%>
                        <%= link_to 'Edit', edit_review_path(r)%>
                        <%= link_to 'Delete', r, method: :delete, data: { confirm: 'Are you sure?' }%>
                      <% end %>
                    <% end %>
                  </div>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
</div>