config/routes.rb
Rails.application.routes.draw do
  resources :reviews, :pets, :locations, :types, :topics,  :comments, :users
  devise_for :users, path: '', path_names:{ sign_in: 'login',  sign_out: 'logout', sessions: ''}
  root 'users#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :review
  def set_user!(user)
    self.user_id = user.id
    self.save!
  end
end

app/models/location.rb
class Location < ApplicationRecord
    has_many :pet, dependent: :destroy
end

app/models/pet.rb
class Pet < ApplicationRecord
  belongs_to :user
  belongs_to :location
  has_many :review, dependent: :destroy
  has_many :pet_type, dependent: :destroy
  has_many :type, through: :pet_type
  mount_uploader :image, ImageUploader

  def set_user!(user)
    self.user_id = user.id
    self.save!
  end
end

app/models/pet_type.rb
class PetType < ApplicationRecord
  belongs_to :type
  belongs_to :pet
end

app/models/phrase.rb
class Phrase < ApplicationRecord
  belongs_to :user
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :pet
  belongs_to :user
  has_many :comment, dependent: :destroy
  has_many :review_topic, dependent: :destroy
  has_many :topic, through: :review_topic
  def set_user!(user)
    self.user_id = user.id
    self.save!
  end
end

app/models/review_topic.rb
class ReviewTopic < ApplicationRecord
  belongs_to :review
  belongs_to :topic
end

app/models/topic.rb
class Topic < ApplicationRecord
    has_many :review_topic, dependent: :destroy
    has_many :review, through: :review_topic
end

app/models/type.rb
class Type < ApplicationRecord
    has_many :pet_type, dependent: :destroy
    has_many :pet, through: :pet_type
end

app/models/user.rb
class User < ApplicationRecord
  has_many :pet, dependent: :destroy
  has_many :review, dependent: :destroy
  has_many :comment, dependent: :destroy
  has_one :phrase, dependent: :destroy
  mount_uploader :profile_picture, ImageUploader
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :update, :destroy]
  before_action :set_pet, only: [:show, :edit, :update, :destroy]

  # GET /pets
  # GET /pets.json
  def index
    @pets = Pet.all
  end

  # GET /pets/1
  # GET /pets/1.json
  def show
    review = @pet.review
    @pet.rating = review.average(:rating)
  end

  # GET /pets/new
  def new
    @pet = Pet.new
  end

  # GET /pets/1/edit
  def edit
  end

  # POST /pets
  # POST /pets.json
  def create
    @pet = Pet.new(pet_params)
    @pet.set_user!(current_user)
  
    respond_to do |format|
      if @pet.save
        format.html { redirect_to @pet}
        format.json { render :show, status: :created, location: @pet }
      else
        format.html { render :new }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pets/1
  # PATCH/PUT /pets/1.json
  def update
    respond_to do |format|
      if @pet.update(pet_params)
        format.html { redirect_to @pet}
        format.json { render :show, status: :ok, location: @pet }
      else
        format.html { render :edit }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pets/1
  # DELETE /pets/1.json
  def destroy
    @pet.destroy
    respond_to do |format|
      format.html { redirect_to users_url}
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pet
      @pet = Pet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pet_params
      params.require(:pet).permit(:names, :date_of_birth, :rating, :location_id, :image, type_ids: [])
    end
end

app/controllers/types_controller.rb
class TypesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :update, :destroy]
  before_action :set_type, only: [:show, :edit, :update, :destroy]

  # GET /types
  # GET /types.json
  def index
    @types = Type.all
  end

  # GET /types/1
  # GET /types/1.json
  def show
  end

  # GET /types/new
  def new
    @type = Type.new
  end

  # GET /types/1/edit
  def edit
  end

  # POST /types
  # POST /types.json
  def create
    @type = Type.new(type_params)

    respond_to do |format|
      if @type.save
        format.html { redirect_to types_url}
        format.json { render :show, status: :created, location: @type }
      else
        format.html { render :new }
        format.json { render json: @type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /types/1
  # PATCH/PUT /types/1.json
  def update
    respond_to do |format|
      if @type.update(type_params)
        format.html { redirect_to types_url}
        format.json { render :show, status: :ok, location: @type }
      else
        format.html { render :edit }
        format.json { render json: @type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /types/1
  # DELETE /types/1.json
  def destroy
    @type.destroy
    respond_to do |format|
      format.html { redirect_to types_url}
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_type
      @type = Type.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def type_params
      params.require(:type).permit(:name, :description)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:index, :show, :edit, :update, :destroy]
  before_action :set_user, only: [:index, :show, :edit, :update, :destroy]
  after_action :verify_authorized

  # GET /users
  # GET /users.json
  def index
    authorize User
  end

  # GET /users/1
  # GET /users/1.json
  def show
    authorize User
  end

  # GET /users/1/edit
  def edit
    authorize User
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    authorize User
    respond_to do |format|
      if @user.update(user_params.except(:phrase_description))
        @phrase.update(description: user_params[:phrase_description])
        format.html { redirect_to users_url}
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    authorize User
    @user.destroy
    respond_to do |format|
      format.html { redirect_to reviews_url}
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(current_user.id)
      @phrase = Phrase.find_or_create_by(user_id: current_user.id)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:names, :lastnames, :date_of_birth, :profile_picture, :phrase_description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/types/_form.html.erb
<%= form_with(model: type, local: true) do |form| %>
  <% if type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(type.errors.count, "error") %> prohibited this type from being saved:</h2>

      <ul>
      <% type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, class:"form-control" %>
  </div>

  <div class="actions float-right">
    <%= form.submit 'Save Type', :class => "btn btn-primary my-2"%>
  </div>
<% end %>

app/views/types/edit.html.erb
<div class="card">
  <div class="card-body">
    <h5 class="card-title"><h1>Editing Type</h1></h5>
    <%= render 'form', type: @type %>
    <%= link_to 'Back', types_path, class:"btn btn-primary my-2" %>
  </div>
</div>

app/views/types/index.html.erb
<main role="main">
      <section class="jumbotron text-center">
        <div class="container">
          <h1 class="jumbotron-heading">Types</h1>
        </div>
      </section>
      <div class="py-5 bg-light">
        <div class="container">
          <div class="row">
            <% @types.each do |type| %>
              <div class="col-md-4">
                <div class="card mb-4 shadow-sm">
                  <div class="card-body">
                    <h5 class="card-title"><%= type.name %></h5>
                    <p class="card-text"><td><%= type.description %></td></p>
                    <div class="d-flex justify-content-between align-items-center">
                      <div class="btn-group">
                        <%= link_to 'Pets', type, class:"btn btn-sm btn-outline-primary"%>
                        <% if user_signed_in?%>
                          <%= link_to 'Edit', edit_type_path(type), class:"btn btn-sm btn-outline-secondary"%>
                          <%= link_to 'Delete', type, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-sm btn-outline-secondary" %>
                        <% end %>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
</main>

<footer class="text-muted">
    <div class="container">
      <p class="float-right">
        <%= link_to 'New Type', new_type_path, class:"btn btn-primary my-2"%>
      </p>
    </div>
</footer>

app/views/types/new.html.erb
<div class="card">
  <div class="card-body">
    <h5 class="card-title"><h1>New Type</h1></h5>
    <%= render 'form', type: @type %>
    <%= link_to 'Back', types_path, class:"btn btn-primary my-2" %>
  </div>
</div>

app/views/types/show.html.erb
<div class="card-columns">
  <% @type.pet.each do |pet| %>
    <div class="card">
      <%= image_tag(pet.image.url, alt: "/assets/pet.png", class: "card-img-top") if pet.image? %>
      <div class="card-body">
        <h5 class="card-title"><%= pet.names%></h5>
        <h6 class="card-subtitle mb-2 text-muted"><%= pet.rating %></h6>
        <p class="card-text">
          <%= pet.location.city %>,
          <%= pet.location.state %>,
          <%= pet.location.country %>
        </p>
        <div class="d-flex justify-content-between align-items-center">
          <div class="btn-group">
            <%= link_to 'Review', new_review_path(:pet => pet), class:"btn btn-sm btn-outline-primary"%>
            <%= link_to 'Profile', pet, class:"btn btn-sm btn-outline-secondary"%>
            <% if user_signed_in?%>
              <% if current_user.id == pet.user.id%>
                <%= link_to 'Edit', edit_pet_path(pet), class:"btn btn-sm btn-outline-secondary"%>
                <%= link_to 'Delete', pet, method: :delete, data: { confirm: 'Are you sure?'}, class:"btn btn-sm btn-outline-secondary"%>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>