config/routes.rb
Rails.application.routes.draw do
  resources :reviews, :pets, :locations, :types, :topics,  :comments, :users
  devise_for :users, path: '', path_names:{ sign_in: 'login',  sign_out: 'logout', sessions: ''}
  root 'users#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/location.rb
class Location < ApplicationRecord
    has_many :pet, dependent: :destroy
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :update, :destroy]
  before_action :set_location, only: [:show, :edit, :update, :destroy]

  # GET /locations
  # GET /locations.json
  def index
    @locations = Location.all
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
    @pets = @location.pet
  end

  # GET /locations/new
  def new
    @location = Location.new
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(location_params)

    respond_to do |format|
      if @location.save
        format.html { redirect_to locations_url}
        format.json { render :show, status: :created, location: @location }
      else
        format.html { render :new }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1
  # PATCH/PUT /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to locations_url }
        format.json { render :show, status: :ok, location: @location }
      else
        format.html { render :edit }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location.destroy
    respond_to do |format|
      format.html { redirect_to locations_url}
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def location_params
      params.require(:location).permit(:city, :state, :country)
    end
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/locations/_form.html.erb
<%= form_with(model: location, local: true) do |form| %>
  <% if location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% location.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :city %>
    <%= form.text_field :city, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :state %>
    <%= form.text_field :state, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :country %>
    <%= form.text_field :country, class:"form-control" %>
  </div>

  <div class="actions float-right">
    <%= form.submit 'Save Location', :class => "btn btn-primary my-2"%>
  </div>
<% end %>

app/views/locations/edit.html.erb
<div class="card">
  <div class="card-body">
    <h5 class="card-title"><h1>Editing Location</h1></h5>
    <%= render 'form', location: @location %>
    <%= link_to 'Back', locations_path, class:"btn btn-primary my-2" %>
  </div>
</div>

app/views/locations/index.html.erb
<main role="main">
      <section class="jumbotron text-center">
        <div class="container">
          <h1 class="jumbotron-heading">Locations</h1>
        </div>
      </section>
      <div class="py-5 bg-light">
        <div class="container">
          <div class="row">
            <% @locations.each do |location| %>
              <div class="col-md-4">
                <div class="card mb-4 shadow-sm">
                  <div class="card-body">
                    <h5 class="card-title"><%= location.city %></h5>
                    <h5 class="card-subtitle mb-2 text-muted"><%= location.state %></h5>
                    <p class="card-text"><td><%= location.country %></td></p>
                    <div class="d-flex justify-content-between align-items-center">
                      <div class="btn-group">
                        <%= link_to 'Pets', location, class:"btn btn-sm btn-outline-primary"%>
                        <% if user_signed_in?%>
                          <%= link_to 'Edit', edit_location_path(location), class:"btn btn-sm btn-outline-secondary"%>
                          <%= link_to 'Delete', location, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-sm btn-outline-secondary" %>
                        <% end %>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
</main>

<footer class="text-muted">
    <div class="container">
      <p class="float-right">
        <%= link_to 'New Location', new_location_path, class:"btn btn-primary my-2"%>
      </p>
    </div>
</footer>

app/views/locations/new.html.erb
<div class="card">
  <div class="card-body">
    <h5 class="card-title"><h1>New Location</h1></h5>
    <%= render 'form', location: @location %>
    <%= link_to 'Back', locations_path, class:"btn btn-primary my-2" %>
  </div>
</div>

app/views/locations/show.html.erb
<div class="card-columns">
  <% @location.pet.each do |pet| %>
    <div class="card">
      <%= image_tag(pet.image.url, alt: "/assets/pet.png", class: "card-img-top") if pet.image? %>
      <div class="card-body">
        <h5 class="card-title"><%= pet.names%></h5>
        <h6 class="card-subtitle mb-2 text-muted"><%= pet.rating %></h6>
        <p class="card-text">
          <%= pet.location.city %>,
          <%= pet.location.state %>,
          <%= pet.location.country %>
        </p>
        <div class="d-flex justify-content-between align-items-center">
          <div class="btn-group">
            <%= link_to 'Review', new_review_path(:pet => pet), class:"btn btn-sm btn-outline-primary"%>
            <%= link_to 'Profile', pet, class:"btn btn-sm btn-outline-secondary"%>
            <% if user_signed_in?%>
              <% if current_user.id == pet.user.id%>
                <%= link_to 'Edit', edit_pet_path(pet), class:"btn btn-sm btn-outline-secondary"%>
                <%= link_to 'Delete', pet, method: :delete, data: { confirm: 'Are you sure?'}, class:"btn btn-sm btn-outline-secondary"%>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>