config/routes.rb
Rails.application.routes.draw do
  resources :reviews, :pets, :locations, :types, :topics,  :comments, :users
  devise_for :users, path: '', path_names:{ sign_in: 'login',  sign_out: 'logout', sessions: ''}
  root 'users#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :review
  def set_user!(user)
    self.user_id = user.id
    self.save!
  end
end

app/models/location.rb
class Location < ApplicationRecord
    has_many :pet, dependent: :destroy
end

app/models/pet.rb
class Pet < ApplicationRecord
  belongs_to :user
  belongs_to :location
  has_many :review, dependent: :destroy
  has_many :pet_type, dependent: :destroy
  has_many :type, through: :pet_type
  mount_uploader :image, ImageUploader

  def set_user!(user)
    self.user_id = user.id
    self.save!
  end
end

app/models/pet_type.rb
class PetType < ApplicationRecord
  belongs_to :type
  belongs_to :pet
end

app/models/phrase.rb
class Phrase < ApplicationRecord
  belongs_to :user
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :pet
  belongs_to :user
  has_many :comment, dependent: :destroy
  has_many :review_topic, dependent: :destroy
  has_many :topic, through: :review_topic
  def set_user!(user)
    self.user_id = user.id
    self.save!
  end
end

app/models/review_topic.rb
class ReviewTopic < ApplicationRecord
  belongs_to :review
  belongs_to :topic
end

app/models/topic.rb
class Topic < ApplicationRecord
    has_many :review_topic, dependent: :destroy
    has_many :review, through: :review_topic
end

app/models/type.rb
class Type < ApplicationRecord
    has_many :pet_type, dependent: :destroy
    has_many :pet, through: :pet_type
end

app/models/user.rb
class User < ApplicationRecord
  has_many :pet, dependent: :destroy
  has_many :review, dependent: :destroy
  has_many :comment, dependent: :destroy
  has_one :phrase, dependent: :destroy
  mount_uploader :profile_picture, ImageUploader
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :update, :destroy]
  before_action :set_pet, only: [:show, :edit, :update, :destroy]

  # GET /pets
  # GET /pets.json
  def index
    @pets = Pet.all
  end

  # GET /pets/1
  # GET /pets/1.json
  def show
    review = @pet.review
    @pet.rating = review.average(:rating)
  end

  # GET /pets/new
  def new
    @pet = Pet.new
  end

  # GET /pets/1/edit
  def edit
  end

  # POST /pets
  # POST /pets.json
  def create
    @pet = Pet.new(pet_params)
    @pet.set_user!(current_user)
  
    respond_to do |format|
      if @pet.save
        format.html { redirect_to @pet}
        format.json { render :show, status: :created, location: @pet }
      else
        format.html { render :new }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pets/1
  # PATCH/PUT /pets/1.json
  def update
    respond_to do |format|
      if @pet.update(pet_params)
        format.html { redirect_to @pet}
        format.json { render :show, status: :ok, location: @pet }
      else
        format.html { render :edit }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pets/1
  # DELETE /pets/1.json
  def destroy
    @pet.destroy
    respond_to do |format|
      format.html { redirect_to users_url}
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pet
      @pet = Pet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pet_params
      params.require(:pet).permit(:names, :date_of_birth, :rating, :location_id, :image, type_ids: [])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Web</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <nav class="navbar navbar-dark fixed-top bg-dark flex-md-nowrap p-0 shadow">
      <a href= <%= users_path %> class="navbar-brand col-sm-2 col-md-1 mr-0"> Home</a>
      <a href= <%= pets_path %> class="navbar-brand col-s2 col-m1 mr-0"> Pets</a>
      <a href= <%= reviews_path %> class="navbar-brand col-s2 col-m1 mr-0"> Reviews</a>
      <a href= <%= topics_path %> class="navbar-brand col-s2 col-m1 mr-0"> Topics</a>
      <a href= <%= types_path %> class="navbar-brand col-s2 col-m1 mr-0"> Types</a>
      <a href= <%= locations_path %> class="navbar-brand col-s2 col-m1 mr-0"> Locations</a>
      <% if user_signed_in?%>
        <%= link_to 'Sign Out', destroy_user_session_path, :method => :delete, class:"nav-link"%>
      <% else%>
        <div class="btn-group">
          <%= link_to 'Sign In', new_user_session_path, class:"nav-link"%>
          <%= link_to 'Sign Up', new_user_registration_path, class:"nav-link"%>
        </div>
      <% end %>
    </nav>
    <%= yield %>
  </body>

</html>